import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  vrchatSidebar: [{ type: 'autogenerated', dirName: 'vrchat' }]
};

export default sidebars;
